"""The database's structure, versioned as text.

``oilwatch/db.py`` holds the CREATE statements *and* then migrates an existing
database in place: ``valid_until``, ``reason``, ``kind`` and ``covers_through``
each arrived after the first release as an ``ALTER``. Reading that code tells you
what a database becomes; it does not show the shape an install actually has, and
the migrations are the part that is easy to get wrong (§12.4 of the checklist).

So the effective schema is written here: every table, index and column a fresh
``init_schema`` produces, and no rows. ``docs/schema.sql`` rather than an empty
``oilwatch.sqlite`` because the point is to be readable in a diff — an empty
database file reviews as "binary files differ", which is the same as not having
one. The live database itself stays untracked: it holds the owner's postcode, his
purchase, his discount codes and his mail, which is what
``tools/build_snapshot.py`` exists to keep out of the export.

    python tools/dump_schema.py [--check]

``--check`` reports whether the committed file still matches the code, and writes
nothing either way.

**Generated, not hand-written.** A schema file maintained by hand drifts from the
code the moment a column is added, so the suite compares the committed file with
what this produces and fails when they disagree — the same guard the price-history
export has, for the same reason.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from oilwatch.config import CHECKOUT_ROOT  # noqa: E402
from oilwatch.db import Database  # noqa: E402

TARGET = CHECKOUT_ROOT / "docs" / "schema.sql"

HEADER = """\
-- The structure of oilwatch.sqlite, as a fresh init_schema produces it.
--
-- Generated by tools/dump_schema.py — edit that, not this. Statements only, no
-- rows: a change to the shape of the database is reviewable here without any of
-- the data those tables hold. The live database is deliberately not committed.
--
-- Regenerate it in the same commit as a schema change; the suite fails when this
-- file and the code disagree.
"""


def collect() -> str:
    """Render the schema a fresh database gets, as text."""
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "schema.sqlite"
        Database(path).init_schema()
        connection = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
        try:
            rows = connection.execute(
                # Tables first, then indexes: an index line reads as an aside until
                # you have seen the table it belongs to.
                "SELECT sql FROM sqlite_master "
                "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' "
                "ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name"
            ).fetchall()
        finally:
            connection.close()

    statements = [f"{row[0]};" for row in rows]
    return HEADER + "\n" + "\n\n".join(statements) + "\n"


def committed_is_current() -> bool:
    """Whether ``docs/schema.sql`` says what the code produces."""
    return TARGET.exists() and TARGET.read_text(encoding="utf-8") == collect()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="report drift instead of writing")
    args = parser.parse_args()

    if args.check:
        if committed_is_current():
            print("schema  in step with the code")
        elif not TARGET.exists():
            print(f"schema  no {TARGET.name} committed, so there is nothing to compare")
        else:
            print("schema  BEHIND - regenerate it with: python tools/dump_schema.py")
        return

    TARGET.write_text(collect(), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(CHECKOUT_ROOT)}")


if __name__ == "__main__":
    main()
