-- The structure of oilwatch.sqlite, as a fresh init_schema produces it.
--
-- Generated by tools/dump_schema.py — edit that, not this. Statements only, no
-- rows: a change to the shape of the database is reviewable here without any of
-- the data those tables hold. The live database is deliberately not committed.
--
-- Regenerate it in the same commit as a schema change; the suite fails when this
-- file and the code disagree.

CREATE TABLE brent_crude (
    observed_at TEXT PRIMARY KEY,
    price_usd_per_barrel REAL NOT NULL,
    source TEXT NOT NULL
);

CREATE TABLE discounts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    supplier_id INTEGER,
    code TEXT,
    amount_gbp REAL NOT NULL,
    min_litres INTEGER,
    max_litres INTEGER,
    expires_at TEXT,
    terms TEXT,
    source TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    raw_text TEXT,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    supplier_id INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    quantity_liters INTEGER NOT NULL,
    agreed_price_per_liter REAL NOT NULL,
    status TEXT NOT NULL,
    reference TEXT,
    notes TEXT,
    raw_payload_json TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE processed_messages (
    message_id TEXT PRIMARY KEY,
    processed_at TEXT NOT NULL
);

CREATE TABLE quote_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    supplier_id INTEGER NOT NULL,
    requested_at TEXT NOT NULL,
    channel TEXT NOT NULL,
    quantity_liters INTEGER,
    postcode TEXT,
    note TEXT,
    answered_at TEXT,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE quotes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    supplier_id INTEGER NOT NULL,
    observed_at TEXT NOT NULL,
    quantity_liters INTEGER NOT NULL,
    status TEXT NOT NULL,
    price_per_liter REAL,
    total_price REAL,
    currency TEXT NOT NULL,
    source TEXT NOT NULL,
    notes TEXT,
    reason TEXT,
    valid_until TEXT,
    raw_payload_json TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE refresh_jobs (
    job_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    started_by TEXT,
    state TEXT NOT NULL DEFAULT 'running',
    total INTEGER,
    done INTEGER NOT NULL DEFAULT 0,
    results_json TEXT,
    error TEXT
);

CREATE TABLE sender_judgements (
    domain TEXT PRIMARY KEY,
    fuel_probability REAL NOT NULL,
    judged_at TEXT NOT NULL,
    covers_through TEXT
);

CREATE TABLE suppliers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    website TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'manual_review',
    kind TEXT NOT NULL DEFAULT 'supplier',
    query TEXT,
    title TEXT,
    snippet TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    latitude REAL,
    longitude REAL,
    distance_miles REAL,
    connector_type TEXT NOT NULL DEFAULT 'manual',
    connector_config_json TEXT NOT NULL DEFAULT '{}',
    notes TEXT,
    first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sweeps (
    started_at TEXT PRIMARY KEY,
    finished_at TEXT,
    started_by TEXT
);

CREATE INDEX idx_quotes_supplier_observed_at ON quotes (supplier_id, observed_at);
